#!/usr/bin/env python3
"""Inline local ES modules into js/bundle.js for file:// compatibility."""

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
JS = ROOT / 'js'

FILES_IN_ORDER = [
    'data-access.js',
    'utils.js',
    'emotions.js',
    'audio.js',
    'starfield.js',
    'constellation.js',
    'interaction.js',
    'ui.js',
    'export.js',
    'app.js',
    'sketch.js',
]

LOCAL_IMPORT = re.compile(r"""^import\s+.+\s+from\s+['"]\./.+['"];?\s*$""", re.MULTILINE)
THREE_IMPORT = re.compile(
    r"""^import\s+.+\s+from\s+['"]three(?:/addons/[^'"]+)?['"];?\s*$""",
    re.MULTILINE,
)


def strip_local_imports(content: str) -> str:
    return LOCAL_IMPORT.sub('', content)


def extract_three_imports(content: str) -> tuple[str, list[str]]:
    imports: list[str] = []

    def replacer(match: re.Match[str]) -> str:
        imports.append(match.group(0).strip())
        return ''

    stripped = THREE_IMPORT.sub(replacer, content)
    return stripped, imports


def strip_exports(content: str) -> str:
    content = re.sub(r'^export\s+', '', content, flags=re.MULTILINE)
    content = re.sub(r'^export\s*\{[^}]+\};?\s*$', '', content, flags=re.MULTILINE)
    return content


def bundle() -> None:
    all_three_imports: list[str] = []
    sections: list[str] = []

    for name in FILES_IN_ORDER:
        source = (JS / name).read_text(encoding='utf-8')
        source = strip_local_imports(source)
        source, three_imports = extract_three_imports(source)
        all_three_imports.extend(three_imports)
        source = strip_exports(source)
        sections.append(f'// --- {name} ---\n{source.strip()}\n')

    seen: set[str] = set()
    unique_imports: list[str] = []
    for imp in all_three_imports:
        if imp not in seen:
            seen.add(imp)
            unique_imports.append(imp)

    header = '// Auto-generated by scripts/bundle-python.py — do not edit by hand.\n'
    imports_block = '\n'.join(unique_imports) + '\n\n' if unique_imports else ''
    body = '\n'.join(sections)

    out = JS / 'bundle.js'
    out.write_text(header + imports_block + body, encoding='utf-8')
    print(f'Wrote {out.relative_to(ROOT)} ({out.stat().st_size} bytes)')


if __name__ == '__main__':
    bundle()
